apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-lrs-prometheus
provisioner: disk.csi.azure.com
parameters:
  skuname: Standard_LRS
  cachingmode: None
  fstype: ext4

reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true