apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./monitoring/monitoring-namespace.yaml
  - ./monitoring/helm-repo.yaml
  - ./monitoring/helm-release.yaml
  - ./monitoring/grafana-ingress.yaml
  - ./csi/csi-config.yaml
  - ./csi/csi-postsql-config.yaml
  - ./ingress-controller-nginx/ingress-namespace.yaml
  - ./ingress-controller-nginx/helmrepo.yaml
  - ./ingress-controller-nginx/helmrelease.yaml
  - ./cert-manager/namespace.yaml
  - ./cert-manager/helmrepo.yaml
  - ./cert-manager/helmrelease.yaml
  - ./cert-manager/clusterissuer.yaml
  - ./monitoring/storage-class-prometheus.yaml
  - ./monitoring/storage-class-grafana.yaml
  - ./monitoring/postgres-exporter/deployment.yaml
  - ./monitoring/postgres-exporter/serivce.yaml
  - ./monitoring/postgres-exporter/service-monitor.yaml
  - ./monitoring/postgres-exporter/configmap.yaml
