apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustomize-apps
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitrepo
  path: ./k8s/k8s_config/apps
  dependsOn:
    - name: kustomize-infra
