apiVersion: v1
kind: Service
metadata:
  name: postgresql-exporter
  namespace: monitoring
  labels: { app: postgresql-exporter }
spec:
  selector: { app: postgresql-exporter }
  ports:
    - name: http
      port: 9187
      targetPort: metrics
